### ISSUE TITLE
hi  is there a sample nuxt project with keycloak integration?

### ISSUE THREAD

**Issue by Meguais** [jotadevelopers/nuxt-keycloak#1]
Is there a sample nuxt project with keycloak integration? thank you

**Comment by jotadevelopers** [comment]
In the playground directory there is an implementation example. However, this module is not yet complete, it lacks some functions to retrieve user roles.

**Comment by jotadevelopers** [comment]
> Is there a sample nuxt project with keycloak integration? thank you

In the playground directory there is an implementation example. However, this module is not yet complete, it lacks some functions to retrieve user roles.
